Add developerMode method
rdkcentral/firebolt-manage-sdk pull request #17
Opened 2022-05-18 17:13 UTC by michaelcfine

Added the developerMode property method

2022-05-18 17:34 UTC, jlacivita requested changes

2022-05-18 17:34 UTC, jlacivita commented on src/modules/device.json
> +                        "xrn:firebolt:capability:settings:device"
We want a specific capability for developer mode, imo.

Propose: `xrn:firebolt:capability:security:developer-mode`

2022-05-18 17:56 UTC, michaelcfine commented on src/modules/device.json
> +                    "name": "property",
Had copied that code; there's lots of it elsewhere that should be fixed. Have separated into two separate tags.

2022-05-23 19:47 UTC, jlacivita commented
Adding Developer Mode setting to Device module.

2022-05-23 19:47 UTC, merged

2023-02-01 17:45 UTC, ottx-automation commented
:tada: This PR is included in version 0.1.0-next.1 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@firebolt-js/manage-sdk/v/0.1.0-next.1)
- [GitHub release](https://github.com/rdkcentral/firebolt-manage-sdk/releases/tag/v0.1.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-19 05:38 UTC, kpears201 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/ripple-rpc/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: