New Provisioning API
rdkcentral/firebolt-manage-sdk pull request #21
Opened 2022-05-23 15:21 UTC by satlead

2022-05-23 17:02 UTC, jlacivita requested changes

2022-05-24 13:31 UTC, jlacivita reviewed
Will let @kpears201 approve if this API is a comprehensive solution. I made some comments on the PUML.

2022-05-24 13:31 UTC, jlacivita commented on src/diagrams/provision.puml
> +        ui -> core:Device.id()
I think `Device.id` returns the back-office ID, not the hardware MAC address?

2022-05-24 13:31 UTC, jlacivita commented on src/diagrams/provision.puml
> +        distributor -> ui:Account Id, Device Id, Distributor Id
Once we settle on which parameters are in the API, update this arrow to match.

2022-05-24 18:19 UTC, kpears201 approved these changes

2022-05-24 18:34 UTC, merged

2022-05-24 21:15 UTC, satlead commented on src/diagrams/provision.puml
> +    participant boot as "Boot"
This file is moved as it was not directly applying to the SDK

2023-02-01 17:45 UTC, ottx-automation commented
:tada: This PR is included in version 0.1.0-next.1 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@firebolt-js/manage-sdk/v/0.1.0-next.1)
- [GitHub release](https://github.com/rdkcentral/firebolt-manage-sdk/releases/tag/v0.1.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-19 05:38 UTC, kpears201 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/ripple-rpc/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: